import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "./provider";
import { SpeedInsights } from "@vercel/speed-insights/next";
import NextAuthProvider from "./provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`inter.className`}>
        <NextAuthProvider>
          <SpeedInsights />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
